### ISSUE TITLE
bounding boxes coordinates for Tek FB et al?

### ISSUE THREAD

**Issue by bafonso** [tobsecret/Awesome_Malaria_Parasite_Imaging_Datasets#1]
I am trying to use the bounding boxes using the coordinates from Tek FB et al dataset. Why do the authors provide 3 points and is it row, col from top left or ?... I've tried a few permutations but so far have not found any that works.

**Comment by tobsecret** [comment]
I'm afraid this is out of the scope of this repo. Probably best to ask the authors themselves.
Took a quick look at the file and yes, the numbers seem odd, not exactly sure what they mean.
